---
abstract: 'A Mongo Driver for Perl'
author:
  - 'Florian Ragwitz <rafl@debian.org>'
  - 'Kristina Chodorow <kristina@mongodb.org>'
  - 'Mike Friedman <mike.friedman@10gen.com>'
build_requires:
  Any::Moose: 0
  Config: 0
  Data::Dump: 0
  Data::Dumper: 0
  Data::Types: 0
  DateTime::Tiny: 0
  Devel::Peek: 0
  Encode: 0
  File::Copy: 0
  File::Slurp: 0
  File::Temp: 0
  FileHandle: 0
  JSON: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
  Try::Tiny: 0
  bigint: 0
  threads: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MongoDB
no_index:
  directory:
    - ext
    - inc
    - t
requires:
  Carp: 0
  Class::MOP::Class: 0
  DateTime: 0
  Digest::MD5: 0
  IO::File: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  Tie::IxHash: 0
  XSLoader: 0
  boolean: 0
  constant: 0
  overload: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://jira.mongodb.org/browse/PERL
  homepage: https://github.com/mongodb/mongo-perl-driver
  repository: git://github.com/mongodb/mongo-perl-driver.git
version: 0.503.2
